name: Devploy-assignment

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: CheckOut code
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: docker build -t devops-assignment .

      - name: Run flask application
        run: docker run -p 5001:5000 devops-assignment

   
